package cluster

import (
	"context"
	"encoding/json"
	"strings"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"

	"github.com/epheo/dotvirt/internal/model"
)

// GVRs for the networking read layer. NADs (gvrNADs) are declared in options.go.
// UDN/CUDN are OVN-K's user-defined networks; NNS/NNCP are nmstate's node network
// state (read-only) and policies (which declare custom uplinks).
var (
	gvrUDN  = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "userdefinednetworks"}
	gvrCUDN = schema.GroupVersionResource{Group: "k8s.ovn.org", Version: "v1", Resource: "clusteruserdefinednetworks"}
	gvrNNS  = schema.GroupVersionResource{Group: "nmstate.io", Version: "v1beta1", Resource: "nodenetworkstates"}
	gvrNNCP = schema.GroupVersionResource{Group: "nmstate.io", Version: "v1", Resource: "nodenetworkconfigurationpolicies"}
)

// NetworkCatalog gathers the whole networking picture as vCenter-style objects:
// the port groups (UDN/CUDN/raw NAD), the physical fabric (Uplinks + node NICs),
// and whether nmstate is present. Read with dotvirt's SA (a scoped tenant usually
// can't list these cluster CRDs); the handler filters project networks to the
// caller's visible namespaces. A failure in any single source is non-fatal: that
// list is left empty and the others fill in.
func (c *Client) NetworkCatalog(ctx context.Context) (model.NetworkInventory, error) {
	dyn, err := c.dynamic()
	if err != nil {
		return model.NetworkInventory{}, err
	}
	inv := model.NetworkInventory{
		Networks:         []model.Network{},
		Uplinks:          []model.Uplink{},
		PhysicalAdapters: []model.PhysicalAdapter{},
	}

	// Port groups. UDN (project) + CUDN (shared) are the typed source of truth;
	// raw NADs are surfaced only when not generated by a UDN/CUDN (those are
	// already represented by their owner, so listing both would double-count).
	//
	// Pass over the NADs first: a CUDN generates one NAD per namespace its
	// namespaceSelector matches, so those namespaces are exactly where the shared
	// network is attachable — collect them, and keep the unowned NADs to surface.
	cudnNS := map[string][]string{}
	var rawNADs []*unstructured.Unstructured
	if items, err := listAllNS(ctx, dyn, gvrNADs); err == nil {
		for i := range items {
			owned := false
			for _, ref := range items[i].GetOwnerReferences() {
				switch ref.Kind {
				case "ClusterUserDefinedNetwork":
					cudnNS[ref.Name] = append(cudnNS[ref.Name], items[i].GetNamespace())
					owned = true
				case "UserDefinedNetwork":
					owned = true
				}
			}
			if !owned && !isSystemNamespace(items[i].GetNamespace()) {
				rawNADs = append(rawNADs, &items[i])
			}
		}
	}

	if items, err := listAllNS(ctx, dyn, gvrUDN); err == nil {
		for i := range items {
			inv.Networks = append(inv.Networks, networkFromUDN(&items[i]))
		}
	}
	if items, err := listAll(ctx, dyn, gvrCUDN); err == nil {
		for i := range items {
			n := networkFromCUDN(&items[i])
			n.Namespaces = cudnNS[n.Name]
			inv.Networks = append(inv.Networks, n)
		}
	}
	for _, nad := range rawNADs {
		inv.Networks = append(inv.Networks, networkFromNAD(nad))
	}

	// Uplinks always include the builtin br-ex (it's OVN-K, present on every node
	// regardless of nmstate); custom uplinks come from NNCP bridge-mappings.
	inv.Uplinks = c.uplinks(ctx, dyn)

	// Physical adapters need nmstate's NodeNetworkState. The GVR not resolving
	// (NoMatch) means the NMState operator isn't installed — leave adapters empty
	// and flag it off so the UI hides "Add Uplink"/adapters rather than showing
	// empty panels.
	if items, err := listAll(ctx, dyn, gvrNNS); err == nil {
		inv.NMStatePresent = true
		for i := range items {
			inv.PhysicalAdapters = append(inv.PhysicalAdapters, adaptersFromNNS(&items[i])...)
		}
	}

	return inv, nil
}

// networkFromUDN decodes a namespace-scoped UserDefinedNetwork. Its network config
// sits directly under spec (spec.topology, spec.<topology>.role/subnets).
func networkFromUDN(u *unstructured.Unstructured) model.Network {
	topology, _, _ := unstructured.NestedString(u.Object, "spec", "topology")
	key := strings.ToLower(topology)
	role, _, _ := unstructured.NestedString(u.Object, "spec", key, "role")
	return model.Network{
		Name:      u.GetName(),
		Kind:      kindFor(topology, role),
		Scope:     model.ScopeProject,
		Namespace: u.GetNamespace(),
		Subnets:   subnetsAt(u.Object, "spec", key),
		Backing:   "UserDefinedNetwork",
		Topology:  topology,
		AttachRef: u.GetNamespace() + "/" + u.GetName(),
	}
}

// networkFromCUDN decodes a cluster-scoped ClusterUserDefinedNetwork. Unlike UDN,
// its config is nested under spec.network (spec.network.topology, …).
func networkFromCUDN(u *unstructured.Unstructured) model.Network {
	topology, _, _ := unstructured.NestedString(u.Object, "spec", "network", "topology")
	key := strings.ToLower(topology)
	role, _, _ := unstructured.NestedString(u.Object, "spec", "network", key, "role")
	n := model.Network{
		Name:      u.GetName(),
		Kind:      kindFor(topology, role),
		Scope:     model.ScopeShared,
		Subnets:   subnetsAt(u.Object, "spec", "network", key),
		Backing:   "ClusterUserDefinedNetwork",
		Topology:  topology,
		AttachRef: u.GetName(),
	}
	if n.Kind == model.NetworkVLAN {
		n.Uplink, _, _ = unstructured.NestedString(u.Object, "spec", "network", "localnet", "physicalNetworkName")
		id, _, _ := unstructured.NestedInt64(u.Object, "spec", "network", "localnet", "vlan", "access", "id")
		n.VLAN = int(id)
	}
	return n
}

// networkFromNAD decodes a raw NetworkAttachmentDefinition (one not generated by a
// UDN/CUDN). The interesting bits live in spec.config, a JSON CNI string.
func networkFromNAD(u *unstructured.Unstructured) model.Network {
	n := model.Network{
		Name:      u.GetName(),
		Kind:      model.NetworkInternal,
		Scope:     model.ScopeProject,
		Namespace: u.GetNamespace(),
		Backing:   "NetworkAttachmentDefinition",
		AttachRef: u.GetNamespace() + "/" + u.GetName(),
	}
	cfg, _, _ := unstructured.NestedString(u.Object, "spec", "config")
	if cfg == "" {
		return n
	}
	var c struct {
		Topology string `json:"topology"`
		VLANID   int    `json:"vlanID"`
		Subnets  string `json:"subnets"`
	}
	if json.Unmarshal([]byte(cfg), &c) != nil {
		return n
	}
	n.Topology = c.Topology
	if c.Topology != "" {
		n.Kind = kindFor(c.Topology, "")
	}
	n.VLAN = c.VLANID
	if c.Subnets != "" {
		n.Subnets = []string{c.Subnets}
	}
	return n
}

// kindFor maps an OVN-K topology + role to the vCenter port-group kind: localnet
// is a VLAN/physical port group; a primary Layer2/3 network is the project's
// "VM Network"; any other Layer2/3 network is an isolated internal port group.
func kindFor(topology, role string) model.NetworkKind {
	if strings.EqualFold(topology, "Localnet") {
		return model.NetworkVLAN
	}
	if strings.EqualFold(role, "Primary") {
		return model.NetworkDefault
	}
	return model.NetworkInternal
}

// subnetsAt extracts a subnets list at prefix. OVN-K writes it two ways: a plain
// []string of CIDRs (Layer2/localnet) or a list of {cidr, hostSubnet} (Layer3).
func subnetsAt(obj map[string]any, prefix ...string) []string {
	raw, found, _ := unstructured.NestedSlice(obj, append(prefix, "subnets")...)
	if !found {
		return nil
	}
	var out []string
	for _, s := range raw {
		switch v := s.(type) {
		case string:
			out = append(out, v)
		case map[string]any:
			if cidr, ok := v["cidr"].(string); ok {
				out = append(out, cidr)
			}
		}
	}
	return out
}

// isSystemNamespace reports whether a namespace holds platform plumbing rather
// than tenant networks — e.g. the openshift-ovn-kubernetes/default NAD that backs
// the cluster's own pod network, which is not a port group a user attaches to.
func isSystemNamespace(ns string) bool {
	return strings.HasPrefix(ns, "openshift-") || ns == "kube-system"
}

// adaptersFromNNS pulls the physical NICs (ethernet/bond) out of one node's
// NodeNetworkState. The NNS name is the node name; interfaces live under
// status.currentState in nmstate's own schema.
func adaptersFromNNS(u *unstructured.Unstructured) []model.PhysicalAdapter {
	ifaces, found, _ := unstructured.NestedSlice(u.Object, "status", "currentState", "interfaces")
	if !found {
		return nil
	}
	node := u.GetName()
	out := []model.PhysicalAdapter{}
	for _, raw := range ifaces {
		m, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		typ := str(m["type"])
		if typ != "ethernet" && typ != "bond" {
			continue // the Physical adapters view is real NICs, not derived devices
		}
		a := model.PhysicalAdapter{
			Node:  node,
			Name:  str(m["name"]),
			Type:  typ,
			MAC:   str(m["mac-address"]),
			State: str(m["state"]),
			Role:  nicRole(m),
		}
		if mtu, ok := toInt(m["mtu"]); ok {
			a.MTU = mtu
		}
		out = append(out, a)
	}
	return out
}

// nicRole reports what a NIC is already doing, from its nmstate controller (the
// master it's enslaved to): a member of br-ex carries the cluster network; any
// other controller means it's already in a bond/bridge; none means it's free.
func nicRole(m map[string]any) string {
	switch ctrl := str(m["controller"]); {
	case ctrl == "":
		return "available"
	case strings.Contains(ctrl, "br-ex"):
		return "cluster-uplink"
	default:
		return "enslaved"
	}
}

// uplinks builds the uplink list: the always-present br-ex default plus any
// declared by an NNCP's ovn.bridge-mappings.
func (c *Client) uplinks(ctx context.Context, dyn dynamic.Interface) []model.Uplink {
	all := c.nodesMatching(ctx, nil)
	out := []model.Uplink{{
		Name: "br-ex", Bridge: "br-ex", Builtin: true, Nodes: all, NodeCount: len(all),
	}}
	if items, err := listAll(ctx, dyn, gvrNNCP); err == nil {
		for i := range items {
			out = append(out, c.uplinksFromNNCP(ctx, &items[i])...)
		}
	}
	return out
}

// uplinksFromNNCP reads the ovn.bridge-mappings an NNCP declares — each one is an
// uplink (physical-network name → OVS bridge) — scoped to the policy's nodes.
func (c *Client) uplinksFromNNCP(ctx context.Context, u *unstructured.Unstructured) []model.Uplink {
	maps, found, _ := unstructured.NestedSlice(u.Object, "spec", "desiredState", "ovn", "bridge-mappings")
	if !found {
		return nil
	}
	sel, _, _ := unstructured.NestedStringMap(u.Object, "spec", "nodeSelector")
	nodes := c.nodesMatching(ctx, sel)
	out := []model.Uplink{}
	for _, raw := range maps {
		m, ok := raw.(map[string]any)
		if !ok || str(m["state"]) == "absent" {
			continue
		}
		out = append(out, model.Uplink{
			Name: str(m["localnet"]), Bridge: str(m["bridge"]),
			Nodes: nodes, NodeCount: len(nodes),
		})
	}
	return out
}

// nodesMatching lists node names matching sel (all nodes when sel is empty).
// Best-effort: a list error yields an empty set rather than failing the catalog.
func (c *Client) nodesMatching(ctx context.Context, sel map[string]string) []string {
	opts := metav1.ListOptions{}
	if len(sel) > 0 {
		opts.LabelSelector = labels.SelectorFromSet(sel).String()
	}
	list, err := c.kube.CoreV1().Nodes().List(ctx, opts)
	if err != nil {
		return nil
	}
	out := make([]string, 0, len(list.Items))
	for i := range list.Items {
		out = append(out, list.Items[i].Name)
	}
	return out
}

func str(v any) string { s, _ := v.(string); return s }

func toInt(v any) (int, bool) {
	switch n := v.(type) {
	case int64:
		return int(n), true
	case float64:
		return int(n), true
	case int:
		return n, true
	}
	return 0, false
}
