// Code generated by tygo. DO NOT EDIT.

//////////
// source: model.go
/*
Package model holds the API-facing types shared across dotvirt's planes.
*/

/**
 * Power is the desired run state derived from a VM manifest's runStrategy.
 */
export type Power = string;
export const PowerOn: Power = "On"; // runStrategy Always / running: true
export const PowerOff: Power = "Off"; // runStrategy Halted / running: false
export const PowerUnknown: Power = "Unknown"; // unset / unrecognized
/**
 * SyncStatus mirrors ArgoCD's per-resource sync state.
 */
export type SyncStatus = string;
export const SyncSynced: SyncStatus = "Synced";
export const SyncOutOfSync: SyncStatus = "OutOfSync";
export const SyncNotTracked: SyncStatus = "NotTracked"; // no ArgoCD Application manages this VM
export const SyncUnknown: SyncStatus = "Unknown";
/**
 * VM is a single virtual machine as shown in the inventory. Fields are populated
 * from whichever planes are active: git always; cluster/argo when enabled.
 */
export interface VM {
  namespace: string;
  name: string;
  /**
   * From git manifest (desired state).
   */
  power: Power;
  cpuCores?: number /* int */;
  memory?: string; // e.g. "2Gi"
  instancetype?: string;
  preference?: string;
  labels?: { [key: string]: string};
  disks?: Disk[];
  networks?: NIC[];
  sourceFile: string; // path within the repo
  /**
   * DRSExclude: the descheduler prefer-no-eviction annotation is on the VM
   * template, so automatic rebalancing skips this VM (drains still migrate it).
   */
  drsExclude?: boolean;
  /**
   * EvictionStrategy is the template's explicit evictionStrategy (LiveMigrate,
   * None, ...); empty means the cluster default.
   */
  evictionStrategy?: string;
  /**
   * From cluster (actual state), when cluster reads are enabled.
   */
  phase?: string; // VMI phase, e.g. Running
  paused?: boolean; // VMI Paused condition (phase stays Running)
  guestIP?: string;
  ips?: string[]; // every guest-reported IP
  nodeName?: string;
  os?: string; // guest-agent OS pretty name
  memoryActual?: string; // current guest memory (hotplug-aware)
  startedAt?: string; // RFC3339; VMI entered Running (for uptime)
  /**
   * Migration is the live (or last) node-to-node move — vCenter's vMotion
   * progress, read from the VMI's migration state. Nil when never migrated.
   */
  migration?: Migration;
  /**
   * From ArgoCD, when enabled.
   */
  sync: SyncStatus;
  health?: string;
  /**
   * SyncError is ArgoCD's apply failure for this VM (e.g. a webhook rejection),
   * surfaced so the UI can explain an OutOfSync VM instead of just flagging it.
   */
  syncError?: string;
}
/**
 * Migration mirrors the VMI's migration state. Active while neither Completed
 * nor Failed is set.
 */
export interface Migration {
  sourceNode?: string;
  targetNode?: string;
  startedAt?: string; // RFC3339
  endedAt?: string; // RFC3339
  completed?: boolean;
  failed?: boolean;
}
/**
 * Disk is a disk device on the VM (from the template).
 */
export interface Disk {
  name: string;
  type?: string; // dataVolume | emptyDisk | containerDisk | cloudInitNoCloud | …
  size?: string; // emptyDisk capacity or dataVolume requested storage
  storageClass?: string; // dataVolume storageClassName (empty = cluster default)
}
/**
 * NIC is a network interface on the VM. Name/Network come from the manifest;
 * MAC/IP are merged from the live VMI status when running.
 */
export interface NIC {
  name: string;
  network?: string; // "pod" or the multus networkName
  mac?: string; // live, from VMI status
  ip?: string; // live, from VMI status
}
/**
 * ProjectNamespace is one namespace bucket within a project: the VMs it holds.
 */
export interface ProjectNamespace {
  namespace: string;
  vms: VM[];
}
/**
 * Project is a tenant in the vCenter-style inventory tree: a named set of
 * namespaces backed by one git repo. Name + Repo come from namespace
 * label/annotation (dotvirt.io/project, dotvirt.io/repo). Error is set (and Repo
 * left empty) when a project's namespaces are labeled but have no usable repo —
 * surfaced as a warning in the UI rather than failing the whole inventory.
 */
export interface Project {
  name: string;
  repo?: string;
  namespaces: ProjectNamespace[];
  error?: string;
  /**
   * GitOps is the project's ArgoCD Application rollup — the sync/health Argo already
   * computes across every object the repo declares, so it reflects segments, network
   * policies and tenancy, not just VMs. Nil when Argo isn't wired or no Application
   * tracks this repo.
   */
  gitOps?: ProjectSync;
}
/**
 * ProjectSync is a project's overall GitOps state, read straight from its managing
 * ArgoCD Application. Operation is the last sync's phase ("Running" = applying,
 * "Failed"/"Error" = apply failed), the cue for a "pending apply" or an alarm that a
 * per-VM view can't give — a merged segment or policy PR that fails to apply shows
 * here even though no VM moved.
 */
export interface ProjectSync {
  sync?: SyncStatus;
  health?: string; // Healthy | Degraded | Progressing | Missing | …
  operation?: string; // operationState.phase: Running | Succeeded | Failed | Error
  syncError?: string; // operationState.message when the last sync didn't succeed
  revision?: string; // short applied git revision
}
/**
 * Inventory is the full multi-project tree. Warnings carry non-fatal degradations
 * (e.g. live or drift state couldn't be read) so the UI can say "status
 * unavailable" instead of silently rendering every VM as stopped / not-tracked.
 * Proposals rides along so the open-PR lane updates over the live stream — a PR
 * merged anywhere (the git poll sees main move) repaints it with no client poll.
 */
export interface Inventory {
  projects: Project[];
  warnings?: string[];
  proposals?: Proposal[];
  /**
   * NetworksVersion is a monotonic watermark that moves when a port group changes
   * (NetworkChanged) or a non-VM object's drift content changes (the argo snapshot's
   * ObjectDriftGen). The network catalog is fetched out-of-band (GET /api/networks,
   * not on this frame), so the frontend re-pulls it when this bumps: a merged segment
   * PR — and its sync badge — then appear live instead of only on reload.
   */
  networksVersion?: number /* uint64 */;
  /**
   * TasksVersion is the same contract for the recent-tasks feed (GET /api/tasks,
   * fetched out-of-band): bumps when an op is recorded or a merged PR lands.
   */
  tasksVersion?: number /* uint64 */;
}
/**
 * Change is one human-readable, YAML-free change item (a semantic diff entry).
 * Action is "change" (From→To), "add" (To), or "remove" (From).
 */
export interface Change {
  field: string;
  action: string; // change | add | remove
  from?: string;
  to?: string;
}
/**
 * EditRequest is the body of an edit: which VM source file, and which fields to
 * change. Power is "On"/"Off"; nil fields are left unchanged.
 */
export interface EditRequest {
  sourceFile: string;
  power?: string;
  cpuCores?: number /* int */;
  memory?: string;
  instancetype?: string;
  preference?: string;
  sizing?: string; // "instancetype" | "custom" — which representation owns CPU/memory
  setLabels?: { [key: string]: string};
  removeLabels?: string[];
  drsExclude?: boolean; // toggle the descheduler prefer-no-eviction annotation
  evictionStrategy?: string; // "" removes (cluster default)
  addDisks?: DiskAdd[];
  removeDisks?: string[];
  addNetworks?: NetworkAdd[];
  removeNetworks?: string[];
  migrateVolumes?: VolumeMigration[]; // storage live migration
  message?: string; // optional commit message; auto-generated when empty
}
/**
 * DiskAdd / NetworkAdd are the add-device entries in an EditRequest body.
 */
export interface DiskAdd {
  name: string;
  size: string;
  storageClass?: string; // blank DataVolume class; empty = cluster default
}
export interface NetworkAdd {
  name: string;
}
/**
 * VolumeMigration moves one disk to another storage class (storage live
 * migration): Name is the volume name on the VM template, StorageClass the
 * target class its replacement DataVolume is provisioned on.
 */
export interface VolumeMigration {
  name: string;
  storageClass: string;
}
/**
 * ProposeRequest is the body of a propose: PR title + description.
 */
export interface ProposeRequest {
  title: string;
  message: string;
}
/**
 * DriftResult is a VM's drift (running vs main) as semantic changes.
 */
export interface DriftResult {
  drift: boolean;
  changes: Change[];
}
/**
 * DraftItem is one pending change rendered for the UI.
 */
export interface DraftItem {
  kind: string; // edit | create | delete
  resource?: string; // "" == vm | network — disambiguates unstage
  namespace: string;
  name: string;
  changes: Change[];
  yaml?: string; // raw/edited manifest for the collapsed view
}
/**
 * DraftView is the whole draft changeset as semantic items.
 */
export interface DraftView {
  base: string;
  branch: string;
  count: number /* int */;
  items: DraftItem[];
}
/**
 * ProposeResult is returned after proposing the draft as a PR.
 */
export interface ProposeResult {
  branch: string;
  pushed: boolean;
  prURL?: string;
  prNumber?: number /* int */;
  compareURL?: string;
  existing?: boolean;
}
/**
 * Proposal is an open pull request backing a project's draft — the staged→PR→
 * synced lifecycle's middle state, surfaced as a Recent Tasks row.
 */
export interface Proposal {
  project: string;
  prNumber: number /* int */;
  prURL: string;
  title?: string;
}
/**
 * TaskEntry is one Recent Tasks row: an imperative runtime op dotvirt performed
 * as the caller ("op"), or a PR merged into a project's base branch ("merge").
 * Server-derived so every browser sees every admin's acts with real attribution;
 * ops live in memory only (the durable audit trail is the cluster's audit log —
 * ops run under the caller's own token), merges re-derive from the forge.
 */
export interface TaskEntry {
  kind: string; // "op" | "merge"
  verb: string;
  namespace?: string; // empty for node-scoped ops
  name?: string; // VM or node name
  project?: string;
  prNumber?: number /* int */;
  prURL?: string;
  title?: string;
  by?: string;
  ok: boolean;
  at: string; // RFC3339
}
/**
 * Permissions is the caller's effective capability set in one namespace — the
 * Permissions tab. Curated to what the UI does under the user's token; config/
 * power/delete are PR-gated (the forge decides), so they aren't rows here.
 */
export interface Permissions {
  namespace: string;
  capabilities: Capability[];
  incomplete?: boolean; // the rules review couldn't enumerate everything
}
/**
 * Capability is one Permissions row: a UI action and whether the caller's token
 * may perform it, with the RBAC behind it for the tooltip.
 */
export interface Capability {
  id: string;
  label: string;
  allowed: boolean;
  detail?: string;
}
/**
 * Commit is one entry in a project's git history, shown in the Changes pane.
 */
export interface Commit {
  hash: string;
  shortHash: string;
  message: string;
  author: string;
  when: string; // RFC3339
  merge?: boolean; // a merge commit (not directly revertable)
}
/**
 * MetricSeries is one line in a chart: a value per timestamp in the parent
 * MetricChart's Times grid (nil = a gap, no sample at that time).
 */
export interface MetricSeries {
  name: string;
  values: (number /* float64 */ | undefined)[];
}
/**
 * MetricChart is one performance chart: a shared time axis plus its series, with a
 * unit hint the UI formats by ("%", "bytes", "Bps", "iops", "ms").
 */
export interface MetricChart {
  key: string;
  title: string;
  unit: string;
  stacked?: boolean; // series partition a whole; render as stacked area
  times: number /* int64 */[]; // unix seconds, the shared x-axis
  series: MetricSeries[];
}
/**
 * VMMetrics is a VM's performance time-series for one range — several charts built
 * from KubeVirt's kubevirt_vmi_* Prometheus metrics, shaped for direct charting.
 */
export interface VMMetrics {
  range: string;
  stepSec: number /* int */;
  charts: MetricChart[];
}
/**
 * UsageMetric is one resource's point-in-time usage for a VM Summary bar — Used of
 * Total in the same unit, with a short recent history for an inline sparkline.
 */
export interface UsageMetric {
  used: number /* float64 */;
  total?: number /* float64 */; // 0 ⇒ no known denominator (show the value alone)
  spark?: number /* float64 */[];
}
/**
 * VMUsage is a VM's live capacity-and-usage for the Summary tab (vCenter's
 * "Capacity and Usage" panel): CPU % of allocated, memory used of allocated,
 * guest-filesystem used of provisioned.
 */
export interface VMUsage {
  updated: number /* int64 */; // unix seconds ("Last updated")
  cpu: UsageMetric; // Used = % of allocated vCPU, Total = 100
  memory: UsageMetric; // bytes; Total = allocated (domain)
  storage: UsageMetric; // bytes; guest filesystem used / capacity
}
/**
 * ClusterMetric is one aggregate resource for the cluster/infrastructure rings:
 * Used now, Allocated (committed to VMs), of Total (node-allocatable capacity).
 */
export interface ClusterMetric {
  used: number /* float64 */;
  allocated?: number /* float64 */; // committed to VMs (vCPU / declared memory)
  total: number /* float64 */; // node-allocatable capacity (the boundary)
  spark?: number /* float64 */[];
}
/**
 * ConsumerVM is one row in a "top consumers" list (a VM ranked by a resource).
 */
export interface ConsumerVM {
  namespace: string;
  name: string;
  value: number /* float64 */;
}
/**
 * ClusterSummary is the aggregate capacity view for the "All VMs" landing — the
 * vCenter cluster-Summary analog: rings (used vs node-allocatable) + VM counts by
 * phase + top-consumer VMs. VM-scoped sums are limited to the caller's namespaces;
 * node capacity is the cluster-wide boundary.
 */
export interface ClusterSummary {
  updated: number /* int64 */;
  cpu: ClusterMetric; // cores
  memory: ClusterMetric; // bytes
  storage: ClusterMetric; // bytes
  vms: { [key: string]: number /* int */}; // phase → count
  topCpu: ConsumerVM[];
  topMemory: ConsumerVM[];
}
/**
 * HostOutlier is one named worker at an edge of the utilization distribution —
 * the only place the payload carries node names, capped to a handful.
 */
export interface HostOutlier {
  node: string;
  pct: number /* float64 */; // CPU utilization percent
  unschedulable?: boolean;
}
/**
 * HostBand is the DRS action band around the mean utilization — the deviation
 * window KubeVirtRelieveAndMigrate actually triggers on. Workers above it are
 * migration sources, workers below it are targets.
 */
export interface HostBand {
  low: number /* float64 */; // percent
  high: number /* float64 */; // percent
  above: number /* int */; // workers over High
  below: number /* int */; // workers under Low
}
/**
 * HostLoad is GET /api/metrics/hosts: the worker CPU-utilization distribution
 * behind the DRS balance card. Deliberately O(1) in cluster size — a fixed
 * 10-bucket histogram plus only the outliers named — so a hundreds-of-workers
 * platform renders the same card as a three-worker lab. Band is set only when
 * a DRS configuration is committed.
 */
export interface HostLoad {
  updated: number /* int64 */;
  workers: number /* int */;
  mean: number /* float64 */; // percent
  buckets: number /* int */[]; // worker count per 10%-wide bucket, [0-10) … [90-100]
  hottest: HostOutlier[]; // ≤5, hottest first
  coldest: HostOutlier[]; // ≤5, coldest first
  band?: HostBand;
}
/**
 * QuotaItem is one resource row of a ResourceQuota: current usage against the
 * hard cap, pre-parsed for direct charting.
 */
export interface QuotaItem {
  resource: string; // e.g. requests.cpu, requests.memory
  used: number /* float64 */;
  hard: number /* float64 */;
  unit: string; // cores | bytes | count
}
/**
 * NamespaceQuota is one ResourceQuota in one namespace — the project capacity
 * band's input. A namespace may carry several (scoped) quotas.
 */
export interface NamespaceQuota {
  namespace: string;
  name: string;
  items: QuotaItem[];
}
/**
 * Alert is one firing Prometheus alert (the dock's Alarms tab). VM is set when
 * the alert's series carries a name label (kubevirt_vmi_* alerts do); Count
 * collapses identical (name, severity, namespace, vm) series.
 */
export interface Alert {
  name: string;
  severity?: string;
  namespace?: string;
  vm?: string;
  count?: number /* int */;
}
/**
 * Event is a Kubernetes Event for a VM (or its VMI), shown in the Monitor tab and
 * the dock's Events lane (which uses Namespace/Name to label which VM it's about).
 */
export interface Event {
  namespace?: string;
  name?: string;
  type: string; // Normal | Warning
  reason: string;
  message: string;
  count?: number /* int32 */;
  object: string; // VirtualMachine | VirtualMachineInstance
  lastSeen?: string; // RFC3339
}
/**
 * Snapshot is a VirtualMachineSnapshot for a VM — the Snapshots tab. KubeVirt
 * snapshots are a flat list (no vCenter-style parent/child tree).
 */
export interface Snapshot {
  name: string;
  created?: string; // RFC3339
  phase?: string; // InProgress | Succeeded | Failed
  readyToUse: boolean;
  indications?: string[]; // Online | GuestAgent | NoGuestAgent
  error?: string;
}
/**
 * Clone is a VirtualMachineClone whose source is a VM — one row in the Clone
 * flow's progress list. The clone controller snapshots the source and restores
 * it into the target VM; the target exists only in the cluster (NotTracked)
 * until adopted into git.
 */
export interface Clone {
  name: string;
  target: string;
  phase?: string; // SnapshotInProgress | RestoreInProgress | CreatingTargetVM | Succeeded | Failed | …
  created?: string; // RFC3339
}
/**
 * UploadStatus is an upload DataVolume's progress (the image-upload flow). Ready
 * (phase UploadReady) means cdi-uploadproxy will accept the bytes; Progress is
 * CDI's import-progress percentage once they're flowing.
 */
export interface UploadStatus {
  phase: string;
  ready: boolean;
  progress?: string;
}
/**
 * UploadToken is the bearer + endpoint the browser POSTs the image to, streaming
 * directly to cdi-uploadproxy (which ships open CORS).
 */
export interface UploadToken {
  token: string;
  uploadUrl: string;
}
/**
 * UploadTarget identifies the upload DataVolume just created.
 */
export interface UploadTarget {
  namespace: string;
  name: string;
}
/**
 * Node is one virtualization host — a node KubeVirt marks schedulable for
 * VMs — as a candidate live-migration target. Ready/Unschedulable let the
 * target picker gray out hosts a migration could not land on.
 */
export interface Node {
  name: string;
  ready: boolean;
  unschedulable?: boolean;
  maintenance?: boolean;
}
/**
 * NodeInfo is a node's maintenance state for the By-Node view: whether it's
 * cordoned, in maintenance mode, and whether the caller's token may cordon it
 * (so the UI hides the actions for users without node-update RBAC).
 * Maintenance is dotvirt's annotation-backed intent marker: it stays set until
 * explicitly exited, even if something else uncordons the node underneath.
 */
export interface NodeInfo {
  name: string;
  unschedulable: boolean;
  maintenance: boolean;
  canCordon: boolean;
}
/**
 * ResyncResult reports which ArgoCD Application was synced.
 */
export interface ResyncResult {
  application: string;
  revision: string;
}
/**
 * Options are the cluster-provided choices for the wizard/editor.
 */
export interface Options {
  instancetypes: Instancetype[];
  preferences: Preference[];
  osImages: OSImage[];
  networks: NetworkOption[];
  storageClasses: StorageClass[];
}
export interface Instancetype {
  name: string;
  cpu: number /* int64 */;
  memory: string;
}
export interface Preference {
  name: string;
  displayName?: string;
}
export interface OSImage {
  name: string;
  namespace: string;
  ready: boolean;
}
export interface NetworkOption {
  name: string;
  namespace: string;
}
export interface StorageClass {
  name: string;
  default?: boolean; // the cluster's default class annotation
}
/**
 * NetworkKind classifies a port group by how a VMware admin reads it.
 */
export type NetworkKind = string;
export const NetworkDefault: NetworkKind = "default"; // primary network — the project's "VM Network"
export const NetworkInternal: NetworkKind = "internal"; // Layer2, no uplink — an isolated port group
export const NetworkVLAN: NetworkKind = "vlan"; // localnet — VLAN-backed, bridged to an uplink
/**
 * NetworkScope is a port group's reach: one project or shared across many.
 */
export type NetworkScope = string;
export const ScopeProject: NetworkScope = "project"; // namespace-scoped (UDN/NAD) — one project
export const ScopeShared: NetworkScope = "shared"; // cluster-scoped (CUDN) — selected projects
/**
 * Network is one Distributed Port Group: a network a VM attaches a NIC to,
 * abstracting a UDN, CUDN, or raw NAD behind vCenter vocabulary.
 */
export interface Network {
  name: string; // the port-group name shown to the user
  kind: NetworkKind; // default | internal | vlan
  scope: NetworkScope; // project | shared
  namespace?: string; // for project-scoped (UDN/NAD)
  vlan?: number /* int */; // 802.1q tag (vlan kind)
  subnets?: string[]; // CIDRs, when IPAM-managed
  uplink?: string; // physicalNetworkName (vlan kind)
  /**
   * AttachRef is how a VM attaches: "namespace/nad". For a CUDN it's the bare
   * name — the generated NAD is namespace-relative, resolved at attach time (6.3).
   */
  attachRef?: string;
  backing: string; // UserDefinedNetwork | ClusterUserDefinedNetwork | NetworkAttachmentDefinition
  topology?: string; // raw OVN-K topology (Layer2|Layer3|Localnet), for the detail drawer
  /**
   * Namespaces is where a shared (CUDN) network is actually attachable — the set
   * where it generated a NAD (its namespaceSelector's effective result). Empty
   * for project-scoped networks (those attach only in their own Namespace).
   */
  namespaces?: string[];
  /**
   * From ArgoCD, when enabled — the same per-object drift VMs carry, so a segment
   * that failed to apply (or is mid-sync) shows its own badge, not just its project's.
   * Empty when Argo isn't wired or no Application manages this object.
   */
  sync?: SyncStatus;
  health?: string;
  syncError?: string;
}
/**
 * Uplink is a physical-network attachment point — the vDS uplink analog: an OVN-K
 * physical-network name mapped to an OVS bridge across a set of nodes. Builtin is
 * the always-present br-ex default (no NNCP required).
 */
export interface Uplink {
  name: string; // physicalNetworkName
  bridge: string; // OVS bridge (br-ex, br-physnet…)
  builtin?: boolean; // the default br-ex uplink
  nodes?: string[]; // nodes carrying the mapping
  nodeCount: number /* int */; // len(Nodes), for the "N/M nodes" badge
  ports?: string[]; // physical NIC(s)/bond enslaved to the bridge
  vlans?: number /* int */[]; // LLDP-discovered VLAN IDs (6.5)
  status?: string; // NNCE rollup: Available | Progressing | Failing (6.5)
}
/**
 * PhysicalAdapter is one node NIC from NodeNetworkState — the host "Physical
 * adapters" view. Role says what the NIC is already doing.
 */
export interface PhysicalAdapter {
  name: string; // eno1, bond0…
  node: string;
  type?: string; // ethernet | bond
  mac?: string;
  state?: string; // up | down
  mtu?: number /* int */;
  role?: string; // cluster-uplink | enslaved | available
}
/**
 * NetworkInventory is GET /api/networks: the port groups the caller may attach to,
 * plus (for node-readers) the physical fabric. NMStatePresent=false means the
 * NMState operator isn't installed, so uplink/adapter discovery is unavailable —
 * the UI hides those affordances rather than showing empty panels.
 */
export interface NetworkInventory {
  networks: Network[];
  uplinks: Uplink[];
  physicalAdapters: PhysicalAdapter[];
  nmstatePresent: boolean;
  /**
   * CanManage is true when the caller may author platform-tier networking
   * (cluster-scoped CUDN): a platform repo is configured AND the caller passes the
   * CUDN-create SSAR. The coarse "any platform authoring" signal that gates the
   * platform-draft view; per-button gating uses Caps.
   */
  canManage: boolean;
  /**
   * Caps is the caller's per-action authoring authority — each field the same SSAR
   * the matching create handler enforces, so a button gated on its field can never
   * offer an action the backend would 403.
   */
  caps: NetworkCaps;
}
/**
 * DRSConfig is the committed DRS configuration, parsed back from the platform
 * repo's KubeDescheduler manifest (defaults resolved).
 */
export interface DRSConfig {
  mode: string; // Predictive | Automatic
  threshold: string; // AsymmetricLow | Low | Medium | High
  intervalSeconds: number /* int */;
  softTainter: boolean;
  evictionNodeLimit: number /* int */;
  evictionTotalLimit: number /* int */;
}
/**
 * DRSGitState is the platform repo's committed DRS state on the base branch.
 */
export interface DRSGitState {
  configured: boolean; // the KubeDescheduler CR is committed
  config?: DRSConfig; // nil when the committed CR doesn't parse (hand-edited)
  psiConfigured: boolean; // the PSI MachineConfig is committed
}
/**
 * DRSDraftState is the caller's pending (staged, not yet proposed) DRS change
 * — the plane between committed and live that the panel's dialog edits.
 */
export interface DRSDraftState {
  config?: DRSConfig; // the staged KubeDescheduler spec
  psi?: boolean; // the PSI MachineConfig is staged too
  disableStaged?: boolean;
}
/**
 * DRSLive is the descheduler's live state, read from the SA-watched
 * KubeDescheduler snapshot — never the cluster per-request.
 */
export interface DRSLive {
  /**
   * APIPresent: the Kube Descheduler Operator's CRD is served. False on a
   * cluster where the operator was never installed — the "not installed" state
   * the panel shows until the first enable-PR merges and OLM installs it.
   */
  apiPresent: boolean;
  /**
   * Synced: the initial LIST landed; until then Deployed=false means
   * "unknown", not "absent". Stale: the API is served but the watch is
   * currently failing (e.g. RBAC not yet reconciled, apiserver outage) — the
   * live fields may be missing or outdated.
   */
  synced: boolean;
  stale?: boolean;
  /**
   * Deployed: a KubeDescheduler CR exists in the cluster.
   */
  deployed: boolean;
  managementState?: string;
  mode?: string;
  profiles?: string[];
  intervalSeconds?: number /* int64 */;
  /**
   * Available mirrors the operator's Available condition; Degraded carries the
   * Degraded condition's message when that condition is true.
   */
  available: boolean;
  degraded?: string;
}
/**
 * DRSView is GET /api/drs: the DRS tier across its planes — the committed git
 * state (flattened), the caller's staged draft, the live operator state — plus
 * the caller's authoring capability, the same SSARs the POST/DELETE handlers
 * enforce. Warning carries a non-fatal degradation (e.g. the platform repo is
 * unreachable, so the committed state is unknown) instead of failing the view.
 */
export interface DRSView {
  DRSGitState: DRSGitState;
  draft?: DRSDraftState;
  live: DRSLive;
  warning?: string;
  canManage: boolean; // kubedeschedulers-create — gates the panel's actions
  canPSI: boolean; // machineconfigs-create — gates the PSI checkbox
}
/**
 * NetworkCaps mirrors each platform-tier create handler's platformScope SSAR, so the
 * UI can show only the authoring buttons the caller can actually use. All false when
 * no platform repo is configured.
 */
export interface NetworkCaps {
  sharedSegment: boolean; // shared / VLAN CUDN
  uplink: boolean; // nmstate NNCP
  namespace: boolean; // namespaces (New Project / Namespace)
  egressIP: boolean; // Tier-0 SNAT
  externalRoute: boolean; // Tier-0 external route
  adminNetworkPolicy: boolean; // cluster-wide admin DFW (ANP/BANP)
}
/**
 * PolicyKind classifies a firewall/routing policy by the NSX-T tier the UI
 * presents: the east-west Distributed Firewall (per-project NetworkPolicy and
 * its cluster-wide admin/baseline overrides), the per-project Gateway Firewall
 * (EgressFirewall on the Tier-1), and the Tier-0 planes (EgressIP SNAT,
 * policy-based external routes).
 */
export type PolicyKind = string;
export const PolicyDFW: PolicyKind = "dfw"; // NetworkPolicy — project east-west rules
export const PolicyAdmin: PolicyKind = "admin"; // AdminNetworkPolicy — cluster-wide, priority-ordered
export const PolicyBaseline: PolicyKind = "baseline"; // BaselineAdminNetworkPolicy — the cluster default
export const PolicyGateway: PolicyKind = "gateway"; // EgressFirewall — project north-south egress
export const PolicyEgressIP: PolicyKind = "egressip"; // EgressIP — Tier-0 source-NAT pool
export const PolicyRoute: PolicyKind = "route"; // AdminPolicyBasedExternalRoute — Tier-0 next hop
/**
 * PolicyRuleView is one rule row as the Security view shows it: direction,
 * action, a human peer summary, and a compact port list. Summaries, not the
 * spec — editing goes through git, the view only has to read well.
 */
export interface PolicyRuleView {
  direction: string; // Ingress | Egress
  action: string; // Allow | Deny | Pass
  peer?: string; // source/destination summary; empty = any
  ports?: string; // "TCP/443, UDP/53"; empty = any
}
/**
 * Policy is one live firewall/routing object rendered in security vocabulary,
 * with the same per-object ArgoCD drift surface networks and VMs carry.
 */
export interface Policy {
  name: string;
  kind: PolicyKind;
  namespace?: string; // empty for cluster-scoped kinds
  backing: string; // the Kubernetes kind behind the row
  priority?: number /* int */; // ANP precedence (lower wins)
  target?: string; // what the policy applies to, summarized
  rules?: PolicyRuleView[];
  sync?: SyncStatus;
  health?: string;
  syncError?: string;
}
/**
 * PolicyInventory is GET /api/policies: the policies the caller may see —
 * namespace-scoped kinds in visible namespaces, cluster-scoped kinds only for
 * callers with the matching platform authoring authority.
 */
export interface PolicyInventory {
  policies: Policy[];
}
/**
 * Template is one VirtualMachineTemplate manifest in a library repo's
 * templates/ directory — a content-library entry (vSphere: a VM template).
 * Name is the file's basename: the deployable identity the API routes carry.
 */
export interface Template {
  name: string;
  library: string; // owning project, or "platform" (the shared library)
  description?: string;
  sourceFile: string; // templates/<name>.yaml
  parameters?: TemplateParameter[];
  instancetype?: string; // blueprint summary, best-effort
  preference?: string;
  yaml: string;
  error?: string; // parse failure — listed, but not deployable
}
/**
 * TemplateParameter mirrors template.kubevirt.io/v1beta1 Parameter, so the
 * wizard's form is exactly what the native CRD will accept later.
 */
export interface TemplateParameter {
  name: string;
  displayName?: string;
  description?: string;
  value?: string;
  generate?: string; // "expression" — value generated from From
  from?: string; // the generator's input pattern
  required?: boolean;
}
/**
 * TemplateList is the content-library listing across the caller's libraries.
 */
export interface TemplateList {
  templates: Template[];
}
/**
 * DeployTemplateRequest renders a library template and stages the resulting VM
 * into the target namespace's project draft.
 */
export interface DeployTemplateRequest {
  library: string;
  template: string;
  namespace: string;
  name?: string; // overrides the NAME parameter; empty → template default (often generated)
  parameters?: { [key: string]: string};
  powerOn?: boolean; // boot the VM once it syncs (templates blueprint Halted)
}
/**
 * UpdateTemplateRequest replaces a library template's manifest — editing a
 * content-library item. The file updates when the library's PR merges.
 */
export interface UpdateTemplateRequest {
  library: string;
  name: string;
  yaml: string;
}
/**
 * SaveTemplateRequest derives a template from an existing VM's git manifest and
 * stages it into the chosen library ("Clone to Template").
 */
export interface SaveTemplateRequest {
  library: string;
  name: string;
  description?: string;
  sourceNamespace: string;
  sourceName: string;
}
