---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dotvirt-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - deletecollection
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - serviceaccounts
  - services
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  verbs:
  - create
  - deletecollection
  - patch
- apiGroups:
  - dotvirt.io
  resources:
  - dotvirts
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - dotvirt.io
  resources:
  - dotvirts/finalizers
  verbs:
  - update
- apiGroups:
  - dotvirt.io
  resources:
  - dotvirts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - deletecollection
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - dotvirt
  - dotvirt-argocd-apply
  - dotvirt-platform-network-admin
  resources:
  - clusterroles
  verbs:
  - bind
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
