# Subscribe to the dotvirt operator from the self-hosted catalog. Automatic approval
# means a new catalog (CatalogSource image bump) rolls the operator forward.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: dotvirt-operator
  namespace: dotvirt-operator
spec:
  channel: stable-v0
  name: dotvirt-operator
  source: dotvirt-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
