package netstate

import (
	"encoding/json"
	"strings"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	"github.com/epheo/dotvirt/internal/model"
)

// Catalog gathers the whole networking picture as vCenter-style objects from the
// watch-fed stores — a pure in-memory scan, never a cluster call: the port groups
// (UDN/CUDN/raw NAD), the physical fabric (Uplinks + node NICs), and whether nmstate is
// present. The handler filters project networks to the caller's visible namespaces and
// enriches each with ArgoCD drift; empty (pre-sync) stores yield an empty picture the
// caller repaints once NetworkChanged fires.
func (s *Snapshot) Catalog() model.NetworkInventory {
	inv := model.NetworkInventory{
		Networks:         []model.Network{},
		Uplinks:          []model.Uplink{},
		PhysicalAdapters: []model.PhysicalAdapter{},
		NMStatePresent:   s.nmstatePresent.Load(),
	}

	// Pass over the NADs first: a CUDN generates one NAD per namespace its
	// namespaceSelector matches, so those namespaces are exactly where the shared
	// network is attachable — collect them, and keep the unowned NADs to surface (a raw
	// NAD not generated by a UDN/CUDN, which those owners already represent).
	cudnNS := map[string][]string{}
	var rawNADs []*unstructured.Unstructured
	for _, u := range listOf(s.nad) {
		owned := false
		for _, ref := range u.GetOwnerReferences() {
			switch ref.Kind {
			case "ClusterUserDefinedNetwork":
				cudnNS[ref.Name] = append(cudnNS[ref.Name], u.GetNamespace())
				owned = true
			case "UserDefinedNetwork":
				owned = true
			}
		}
		if !owned && !isSystemNamespace(u.GetNamespace()) {
			rawNADs = append(rawNADs, u)
		}
	}

	for _, u := range listOf(s.udn) {
		inv.Networks = append(inv.Networks, networkFromUDN(u))
	}
	for _, u := range listOf(s.cudn) {
		n := networkFromCUDN(u)
		n.Namespaces = cudnNS[n.Name]
		inv.Networks = append(inv.Networks, n)
	}
	for _, nad := range rawNADs {
		inv.Networks = append(inv.Networks, networkFromNAD(nad))
	}

	inv.Uplinks = s.uplinks()
	for _, u := range listOf(s.nns) {
		inv.PhysicalAdapters = append(inv.PhysicalAdapters, adaptersFromNNS(u)...)
	}
	return inv
}

// uplinks builds the uplink list: the always-present builtin br-ex (OVN-K, on every
// node regardless of nmstate) plus any declared by an NNCP's ovn.bridge-mappings.
func (s *Snapshot) uplinks() []model.Uplink {
	all := s.nodesMatching(nil)
	out := []model.Uplink{{
		Name: "br-ex", Bridge: "br-ex", Builtin: true, Nodes: all, NodeCount: len(all),
	}}
	for _, u := range listOf(s.nncp) {
		out = append(out, s.uplinksFromNNCP(u)...)
	}
	return out
}

// uplinksFromNNCP reads the ovn.bridge-mappings an NNCP declares — each one is an
// uplink (physical-network name → OVS bridge) — scoped to the policy's nodes.
func (s *Snapshot) uplinksFromNNCP(u *unstructured.Unstructured) []model.Uplink {
	maps, found, _ := unstructured.NestedSlice(u.Object, "spec", "desiredState", "ovn", "bridge-mappings")
	if !found {
		return nil
	}
	sel, _, _ := unstructured.NestedStringMap(u.Object, "spec", "nodeSelector")
	nodes := s.nodesMatching(sel)
	out := []model.Uplink{}
	for _, raw := range maps {
		m, ok := raw.(map[string]any)
		if !ok || str(m["state"]) == "absent" {
			continue
		}
		out = append(out, model.Uplink{
			Name: str(m["localnet"]), Bridge: str(m["bridge"]),
			Nodes: nodes, NodeCount: len(nodes),
		})
	}
	return out
}

// nodesMatching returns the names of cached nodes matching sel (all nodes when sel is
// empty), filtered in memory — the node cache stands in for a per-request node LIST.
func (s *Snapshot) nodesMatching(sel map[string]string) []string {
	s.nodesMu.RLock()
	defer s.nodesMu.RUnlock()
	out := make([]string, 0, len(s.nodes))
	for _, n := range s.nodes {
		if matchesLabels(n.Labels, sel) {
			out = append(out, n.Name)
		}
	}
	return out
}

func matchesLabels(have, want map[string]string) bool {
	for k, v := range want {
		if have[k] != v {
			return false
		}
	}
	return true
}

// networkFromUDN decodes a namespace-scoped UserDefinedNetwork. Its network config
// sits directly under spec (spec.topology, spec.<topology>.role/subnets).
func networkFromUDN(u *unstructured.Unstructured) model.Network {
	topology, _, _ := unstructured.NestedString(u.Object, "spec", "topology")
	key := strings.ToLower(topology)
	role, _, _ := unstructured.NestedString(u.Object, "spec", key, "role")
	return model.Network{
		Name:      u.GetName(),
		Kind:      kindFor(topology, role),
		Scope:     model.ScopeProject,
		Namespace: u.GetNamespace(),
		Subnets:   subnetsAt(u.Object, "spec", key),
		Backing:   "UserDefinedNetwork",
		Topology:  topology,
		AttachRef: u.GetNamespace() + "/" + u.GetName(),
	}
}

// networkFromCUDN decodes a cluster-scoped ClusterUserDefinedNetwork. Unlike UDN,
// its config is nested under spec.network (spec.network.topology, …).
func networkFromCUDN(u *unstructured.Unstructured) model.Network {
	topology, _, _ := unstructured.NestedString(u.Object, "spec", "network", "topology")
	key := strings.ToLower(topology)
	role, _, _ := unstructured.NestedString(u.Object, "spec", "network", key, "role")
	n := model.Network{
		Name:      u.GetName(),
		Kind:      kindFor(topology, role),
		Scope:     model.ScopeShared,
		Subnets:   subnetsAt(u.Object, "spec", "network", key),
		Backing:   "ClusterUserDefinedNetwork",
		Topology:  topology,
		AttachRef: u.GetName(),
	}
	if n.Kind == model.NetworkVLAN {
		n.Uplink, _, _ = unstructured.NestedString(u.Object, "spec", "network", "localnet", "physicalNetworkName")
		id, _, _ := unstructured.NestedInt64(u.Object, "spec", "network", "localnet", "vlan", "access", "id")
		n.VLAN = int(id)
	}
	return n
}

// networkFromNAD decodes a raw NetworkAttachmentDefinition (one not generated by a
// UDN/CUDN). The interesting bits live in spec.config, a JSON CNI string.
func networkFromNAD(u *unstructured.Unstructured) model.Network {
	n := model.Network{
		Name:      u.GetName(),
		Kind:      model.NetworkInternal,
		Scope:     model.ScopeProject,
		Namespace: u.GetNamespace(),
		Backing:   "NetworkAttachmentDefinition",
		AttachRef: u.GetNamespace() + "/" + u.GetName(),
	}
	cfg, _, _ := unstructured.NestedString(u.Object, "spec", "config")
	if cfg == "" {
		return n
	}
	var c struct {
		Topology string `json:"topology"`
		VLANID   int    `json:"vlanID"`
		Subnets  string `json:"subnets"`
	}
	if json.Unmarshal([]byte(cfg), &c) != nil {
		return n
	}
	n.Topology = c.Topology
	if c.Topology != "" {
		n.Kind = kindFor(c.Topology, "")
	}
	n.VLAN = c.VLANID
	if c.Subnets != "" {
		n.Subnets = []string{c.Subnets}
	}
	return n
}

// kindFor maps an OVN-K topology + role to the vCenter port-group kind: localnet
// is a VLAN/physical port group; a primary Layer2/3 network is the project's
// "VM Network"; any other Layer2/3 network is an isolated internal port group.
func kindFor(topology, role string) model.NetworkKind {
	if strings.EqualFold(topology, "Localnet") {
		return model.NetworkVLAN
	}
	if strings.EqualFold(role, "Primary") {
		return model.NetworkDefault
	}
	return model.NetworkInternal
}

// subnetsAt extracts a subnets list at prefix. OVN-K writes it two ways: a plain
// []string of CIDRs (Layer2/localnet) or a list of {cidr, hostSubnet} (Layer3).
func subnetsAt(obj map[string]any, prefix ...string) []string {
	raw, found, _ := unstructured.NestedSlice(obj, append(prefix, "subnets")...)
	if !found {
		return nil
	}
	var out []string
	for _, s := range raw {
		switch v := s.(type) {
		case string:
			out = append(out, v)
		case map[string]any:
			if cidr, ok := v["cidr"].(string); ok {
				out = append(out, cidr)
			}
		}
	}
	return out
}

// isSystemNamespace reports whether a namespace holds platform plumbing rather
// than tenant networks — e.g. the openshift-ovn-kubernetes/default NAD that backs
// the cluster's own pod network, which is not a port group a user attaches to.
func isSystemNamespace(ns string) bool {
	return strings.HasPrefix(ns, "openshift-") || ns == "kube-system"
}

// adaptersFromNNS pulls the physical NICs (ethernet/bond) out of one node's
// NodeNetworkState. The NNS name is the node name; interfaces live under
// status.currentState in nmstate's own schema.
func adaptersFromNNS(u *unstructured.Unstructured) []model.PhysicalAdapter {
	ifaces, found, _ := unstructured.NestedSlice(u.Object, "status", "currentState", "interfaces")
	if !found {
		return nil
	}
	node := u.GetName()
	out := []model.PhysicalAdapter{}
	for _, raw := range ifaces {
		m, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		typ := str(m["type"])
		if typ != "ethernet" && typ != "bond" {
			continue // the Physical adapters view is real NICs, not derived devices
		}
		a := model.PhysicalAdapter{
			Node:  node,
			Name:  str(m["name"]),
			Type:  typ,
			MAC:   str(m["mac-address"]),
			State: str(m["state"]),
			Role:  nicRole(m),
		}
		if mtu, ok := toInt(m["mtu"]); ok {
			a.MTU = mtu
		}
		out = append(out, a)
	}
	return out
}

// nicRole reports what a NIC is already doing, from its nmstate controller (the
// master it's enslaved to): a member of br-ex carries the cluster network; any
// other controller means it's already in a bond/bridge; none means it's free.
func nicRole(m map[string]any) string {
	switch ctrl := str(m["controller"]); {
	case ctrl == "":
		return "available"
	case strings.Contains(ctrl, "br-ex"):
		return "cluster-uplink"
	default:
		return "enslaved"
	}
}

func str(v any) string { s, _ := v.(string); return s }

func toInt(v any) (int, bool) {
	switch n := v.(type) {
	case int64:
		return int(n), true
	case float64:
		return int(n), true
	case int:
		return n, true
	}
	return 0, false
}
