package netstate

// The east-west topology questions the trace asks before any policy runs:
// which primary network an endpoint sits on, and which secondary segments two
// endpoints share (an unfiltered layer-2 bypass).

import (
	"sort"
	"strings"

	"github.com/epheo/dotvirt/internal/reflect"
)

// primaryOf resolves the primary network a workload attaches. A default
// multus binding substitutes the named NAD's segment for the pod network, so
// it compares by segment identity, not by the namespace's primary domain;
// otherwise a pod binding resolves the namespace's primary UDN/CUDN, else the
// cluster default. No binding at all means no primary path.
func (s *Snapshot) primaryOf(w TraceWorkload) (key, display string) {
	if w.DefaultNet != "" {
		k, name := s.segmentKey(w.DefaultNet)
		return k, "network " + name
	}
	if !w.PodNet {
		return "", ""
	}
	return s.primaryDomain(w.Namespace)
}

// primaryDomain resolves a namespace's primary network: a Primary-role UDN in
// the namespace, a Primary-role CUDN whose generated NAD sits there, else the
// cluster default network.
func (s *Snapshot) primaryDomain(ns string) (key, display string) {
	for _, u := range reflect.List(s.udn) {
		if u.GetNamespace() != ns {
			continue
		}
		if _, role := udnNetwork(u); strings.EqualFold(role, "Primary") {
			return "udn:" + ns + "/" + u.GetName(), "network " + u.GetName()
		}
	}
	for _, u := range reflect.List(s.cudn) {
		if _, role := cudnNetwork(u); !strings.EqualFold(role, "Primary") {
			continue
		}
		for _, nad := range reflect.List(s.nad) {
			if nad.GetNamespace() != ns {
				continue
			}
			for _, ref := range nad.GetOwnerReferences() {
				if ref.Kind == "ClusterUserDefinedNetwork" && ref.Name == u.GetName() {
					return "cudn:" + u.GetName(), "shared network " + u.GetName()
				}
			}
		}
	}
	return "default", "the cluster default network"
}

// sharedSegments returns the display names of secondary segments both NIC
// sets attach, resolving CUDN-generated NADs to one identity across namespaces.
func (s *Snapshot) sharedSegments(a, b []string) []string {
	seen := map[string]string{}
	for _, ref := range a {
		k, name := s.segmentKey(ref)
		seen[k] = name
	}
	var out []string
	added := map[string]bool{}
	for _, ref := range b {
		k, _ := s.segmentKey(ref)
		if name, ok := seen[k]; ok && !added[k] {
			out = append(out, name)
			added[k] = true
		}
	}
	sort.Strings(out)
	return out
}

// segmentKey resolves one multus ref to a comparable segment identity: NADs
// generated by one CUDN are the same segment in every namespace it spans; a
// UDN-owned or raw NAD is its own.
func (s *Snapshot) segmentKey(ref string) (key, display string) {
	if u, ok := reflect.Get(s.nad, ref); ok {
		for _, r := range u.GetOwnerReferences() {
			switch r.Kind {
			case "ClusterUserDefinedNetwork":
				return "cudn:" + r.Name, r.Name
			case "UserDefinedNetwork":
				return "udn:" + ref, r.Name
			}
		}
	}
	return "nad:" + ref, ref
}

// isLocalnet reports whether a NAD's CNI config declares localnet topology —
// the segment kind with its own path to the physical fabric.
func (s *Snapshot) isLocalnet(ref string) bool {
	u, ok := reflect.Get(s.nad, ref)
	if !ok {
		return false
	}
	c, ok := nadConfig(u)
	return ok && strings.EqualFold(c.Topology, "localnet")
}
